# Site
locale                   : "en-US"
title                    : "Richard F. M. Lim"
title_separator          : "·"
name                     : &name "Richard F. M. Lim"
description              : &description "Richard Lim — geometry of generalization in deep learning, tropical neural networks, and length extrapolation for combinatorial optimization."
url                      : https://rlim-fm.github.io
baseurl                  : ""
repository               : "rlim-fm/rlim-fm.github.io"

author:
  name             : *name
  name_zh          : "林枫眠"
  avatar           : "profile.png"
  email            : "rlim@bowdoin.edu"
  github           : "rlim-fm"
  linkedin         : "richard-lim-fm"
  googlescholar    : https://scholar.google.com/citations?user=KGjOJDUAAAAJ&hl=en

# Collections
collections:
  projects:
    output: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# Build
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

include:
  - files

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor

encoding: "utf-8"
markdown: kramdown
highlighter: rouge
future: true

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
